language: node_js

cache:
  directories:
    - ~/.npm
    
node_js:
  - '12'

git:
  depth: 3

branches:
  only:
    - master

env:
  global:
    - NODE_ENV=dev
    - PORT=3000

script: yarn validate
after_success: yarn coverage
